var rule = {
  title: '[影]青龙影院',
  host: 'https://www.minggejiaoyu.xyz/',
  url: '/vodshow/fyclass--time------fypage---.html',
  searchUrl: '/vodsearch/**----------fypage---.html',
  searchable: 2,
  headers: {'User-Agent': 'MOBILE_UA',},
  timeout: 5000,
  class_parse: '.search-ul.dropdown-hover li;a&&Text;a&&href;/\\w+/(\\d+).html',
  play_parse: true,
  lazy: "js:\n  input = { parse: 1, url: input, js: '' };",
  tab_exclude:'同类型',
  图片来源:'@Referer=https://pic.ssxmovie.shop/',
  double: true,
  推荐: '.minggejiaoyuui-vodlist;.minggejiaoyu-minlg-6;.lazyload&&title;.lazyload&&data-original;.pic-tag&&Text;a&&href;.pic-text&&Text',
  一级: '.minggejiaoyu-minlg-6;.lazyload&&title;.lazyload&&data-original;.pic-tag&&Text;a&&href;.pic-text&&Text',
  二级: {
    title: 'h1.title&&Text;p.data:eq(0) a:eq(0)--span&&Text',
    img: '.lazyload&&data-original',
    desc: 'p.data:eq(1)--.text-muted&&Text;p.data:eq(0) a:eq(2)--span&&Text;p.data:eq(0) a:eq(1)--span&&Text;p.data:eq(2)--span&&Text;p.data:eq(3)--span&&Text',
    content: '.sketch&&Text',
    tabs: '.nav-tabs li',
    lists: '.minggejiaoyuui-content__list:eq(#id)&&a',
    tab_text: 'body&&Text',
    list_text: 'body&&Text',
    list_url: 'a&&href',
  },
  搜索: '#searchList li;.lazyload&&title;.lazyload&&data-original;.pic-tag&&Text;a&&href;.pic-text&&Text',
}