var rule = {
  title: '音范丝',
  host: 'https://www.yinfans.net/',
  url: 't/topic/fyclass/page/fypage[/topic/fyclass]',
  searchUrl: '/vodsearch/**----------fypage---/',
  class_name: '电影&演唱会&4k&影单',
  class_url: 'bluray-movie/movie&bluray-movie/song&4k&special',
  searchable: 2,
  quickSearch: 0,
  filterable: 0,
  headers: {
    'User-Agent': 'MOBILE_UA',
  },
  play_parse: true,
  lazy: "js:\n  let html = request(input);\n  let hconf = html.match(/r player_.*?=(.*?)</)[1];\n  let json = JSON5.parse(hconf);\n  let url = json.url;\n  if (json.encrypt == '1') {\n    url = unescape(url);\n  } else if (json.encrypt == '2') {\n    url = unescape(base64Decode(url));\n  }\n  if (/\\.(m3u8|mp4|m4a|mp3)/.test(url)) {\n    input = {\n      parse: 0,\n      jx: 0,\n      url: url,\n    };\n  } else {\n    input = url && url.startsWith('http') && tellIsJx(url) ? {parse:0,jx:1,url:url}:input;\n  }",
  limit: 6,
  double: true,
  推荐: '.mainleft li;*;*;*;*',
  一级: '.mainleft&&ul li;a&&title;img&&src;.info_category&&Text;a&&href',
  二级: {
    title: 'h1&&Text;.article_container&&p:eq(1)--br&&Text',
    img: '.alignnone&&src',
    desc: '.content_detail:eq(1)&&li:eq(1)&&Text;.content_detail:eq(1)&&li&&a&&Text;.content_detail:eq(1)&&li&&a:eq(1)&&Text;.content_detail:eq(1)&&li:eq(2)&&Text;.content_detail:eq(1)&&li:eq(3)&&Text',
    content: '.article_container&&p:eq(3)--br&&Text',
    tabs: '#btn-group',
    lists: '#cili:eq(#id) td',
  },
  搜索: '*',
}